# Generated by Django 5.0 on 2023-12-10 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='useer',
            new_name='User',
        ),
    ]
