# Generated by Django 5.0 on 2023-12-10 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_useer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
