# Generated by Django 5.0 on 2023-12-10 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_useer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Useer',
        ),
    ]
